# Environment Setup
FROM node:19
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Move rest (consider dockerignore)
COPY . .

# Expose port
EXPOSE 3000

# Run
CMD ["npm", "start"]
