events { worker_connections 1024; }

http {
    upstream api_servers {
        server server-api:3001;
    }

    upstream ws_servers {
        server server-ws:8080;
    }

    # 1. API Load Balancer (HTTP)
    server {
        listen 3001;

        location / {
            proxy_pass http://api_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    # 2. WebSocket Load Balancer (WS)
    server {
        listen 8080;

        location / {
            proxy_pass http://ws_servers;
            
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}