/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A chat create schema
 */
export interface ChatCreate {
  $schema?: string;
  /**
   * Name of the chat
   */
  name: string | null;
  /**
   * Users participanting in the chat
   *
   * @minItems 2
   * @maxItems 256
   */
  users: [
    {
      /**
       * Identifier of the user
       */
      id: string;
      /**
       * Admin user flag information
       */
      isAdmin?: boolean;
      [k: string]: unknown;
    },
    {
      /**
       * Identifier of the user
       */
      id: string;
      /**
       * Admin user flag information
       */
      isAdmin?: boolean;
      [k: string]: unknown;
    },
    ...{
      /**
       * Identifier of the user
       */
      id: string;
      /**
       * Admin user flag information
       */
      isAdmin?: boolean;
      [k: string]: unknown;
    }[]
  ];
  /**
   * Group chat flag information
   */
  isGroup: boolean;
}
