/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A Message create schema
 */
export interface MessageCreate {
  /**
   * Content of the message
   */
  content: (Block | Mark)[];
  /**
   * Identifier of the message replied to
   */
  repliedToId?: string;
}
/**
 * A block type schema
 */
export interface Block {
  /**
   * Type of block
   */
  type: "paragraph" | "ordered-list" | "unordered-list" | "list-item" | "heading-one" | "heading-two";
  /**
   * Content of the block
   */
  children?: (Block | Mark)[];
}
/**
 * A mark type schema
 */
export interface Mark {
  /**
   * The text content of a leaf node
   */
  text: string;
  /**
   * Text formatting option, whether the text is bold
   */
  bold?: boolean;
  /**
   * Text formatting option, whether the text is italicized
   */
  italic?: boolean;
  /**
   * Text formatting option, whether the text is code
   */
  code?: boolean;
  /**
   * Text formatting option, whether the text is underlined
   */
  underline?: boolean;
  /**
   * Text formatting option, whether the text is strikethrough
   */
  strikethrough?: boolean;
}
