/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A signup user schema
 */
export interface UserSignup {
  /**
   * Username of the user
   */
  username: string;
  /**
   * Password of the user
   */
  password: string;
  /**
   * Email of the user
   */
  email: string;
}
