/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A user update body params
 */
export interface UserUpdate {
  /**
   * Username of the user
   */
  username?: string;
  /**
   * Short description of the user
   */
  bio?: string;
}
