/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A signin user schema
 */
export interface UserSignin {
  /**
   * Username or email of the user
   */
  userIdentifier: string;
  /**
   * Password of the user
   */
  password: string;
}
